### ISSUE TITLE
Garry's Log with only 1 Database

### ISSUE THREAD

**Issue by UnReal933** [Sudoplays/Garrys-Log#1]
Hello,

I want to install Garry's Log to my server but my hoster only provide one database, also I tried to change "CREATE TABLE IF NOT EXISTS" with the name of my database.

But I have an error with alter table.

What can I do?

**Comment by Sudoplays** [comment]
A table is inside of the database, you should not need to modify the database.sql file at all.
You should request another database from your hosting provider for the addon, if they won't give you another database, then you can always use one universal database which I do not support or recommend doing.

Your hosting provider may also limit the database size, and if you don't manually prune the logs or archive them you will find your database will easily reach a few hundred megabytes in a few weeks if you have an active server.

**Comment by UnReal933** [comment]
When I upload the database.sql, I have this error:

"#1068 - Multiple primary key defined "

Do you know why?
